### ISSUE TITLE
Issues building llvmlite 0.7.0 on OS X

### ISSUE THREAD

**Issue by cournape** [numba/llvmlite#97]
Hi,

I am having issues building the latest release of llvmlite (0.7.0) for OS X:

Undefined symbols for architecture x86_64:
"typeinfo for llvm::ObjectCache", referenced from:
      typeinfo for LLVMPYObjectCache in executionengine-eJkHKW.o
      ld: symbol(s) not found for architecture x86_64

I am building llvmlite against llvm 3.6.1, using clang from OS X 10.7. I could build llvmlite 0.6.0 against the exact same llvm package (and it seems to work on linux for llvm 3.6.1 and llvmlite 0.7.0).

David

**Comment by pitrou** [comment]
I'm not sure, but perhaps you need to compile LLVM with RTTI enabled? or llvmlite with RTTI disabled?

**Comment by tdsmith** [comment]
I noticed the same thing against Homebrew's default llvm 3.6.2 using clang 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn) from Xcode 6.4 on 10.10.5.

Homebrew's default llvm is indeed built without RTTI. Do you have advice for how to build llvmlite with RTTI disabled, and should I consider that to be an acceptable solution for distributing numba?

**Comment by tdsmith** [comment]
Adding `-fno-rtti` to the `CXX` string in ffi/Makefile.osx yields a working build.

**Comment by cournape** [comment]
Good call, that was exactly the issue.

**Comment by pitrou** [comment]
Yes, that's acceptable. Just make sure the test suite still passes (`python -m llvmlite.tests`).

**Comment by pitrou** [comment]
I don't know if that would be acceptable to add to our Makefile. Perhaps @sklam wants to weigh in.

**Comment by cournape** [comment]
FWIW, numba 0.21.0  + llvmlite 0.7.0 + llvm 3.6.1 passes the whole test suite on os x with that simple change.

**Comment by sklam** [comment]
LLVM disables RTTI by default (http://llvm.org/docs/Packaging.html#c-features).  If we can, we should avoid using RTTI.  So it would be good to have `-fno-rtti` added to our Makefile.

**Comment by pitrou** [comment]
This should hopefully be fixed now.
