### ISSUE TITLE
OS X with homebrew llvm -- pip install fails

### ISSUE THREAD

**Issue by defjaf** [numba/llvmlite#76]
When I try to install the latest llvmlite 0.6.0 with [homebrew](https://github.com/Homebrew/homebrew) llvm 3.6.1, after setting `LLVM_CONFIG=/usr/local/Cellar/llvm/3.6.1/bin/llvm-config` I get the following error:

        initfini.cpp:9:10: fatal error: 'llvm/Config/config.h' file not found
        #include "llvm/Config/config.h"

It appears that `/usr/local/Cellar/llvm/3.6.1/include/llvm/Config/llvm-config.h` exists, but not `config.h`. This can be fixed with a softlink, but it is probably an error either in the homebrew installation or the initfini.cpp file. I have also reported [a version of this error to the homebrew repo](https://github.com/Homebrew/homebrew/issues/41320).

**Comment by pitrou** [comment]
As I answered on the other bug, this is probably because homebrew builds LLVM using cmake, while llvmlite assumes Unix builds use the autotools (`./configure`) method.
We could probably do better here. Out of curiosity, can you paste the contents of your `llvm-config.h` somewhere?

**Comment by tamird** [comment]
https://github.com/llvm-mirror/llvm/commit/90c29494121e3a4cefb5cae5d272178bbc49d3a9#diff-b67911656ef5d18c4ae36cb6741b7965R30 suggests that `config.h` is never intended to be used outside the LLVM build system. `llvm-config.h` seems to be safe, though.

**Comment by pitrou** [comment]
Yes, we can probably switch to always use `llvm-config.h` now that we use LLVM 3.6. `config.h` was required on autotools builds with LLVM 3.5.
