### ISSUE TITLE
No attribute 'test_pycc_tresult' on numba.test()

### ISSUE THREAD

**Issue by ml31415** [numba/llvmlite#203]
I just ran into this when upgrading to 0.28.1 and also reproduced this error message with master:
```
>>> nb.test()
E
======================================================================
ERROR: numba.tests (unittest.loader.LoadTestsFailure)
----------------------------------------------------------------------
AttributeError: 'module' object has no attribute 'test_pycc_tresult'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
False
```
Bug or feature?

There was some merge comment mentioning `test_pycc_tresult` a while ago, though I don't know if this is actually related. For the record, Ubuntu 16.04, LLVM 3.8.0.

**Comment by pitrou** [comment]
You're probably using Python 2.7 and some Python module got renamed, leaving a stale `.pyc` file in the file hierarchy. Are you running from git or did you install Numba using conda?

**Comment by pitrou** [comment]
By the way, you reported this to the llvmlite issue tracker by mistake, it seems.

**Comment by ml31415** [comment]
Stupid me, sorry. I had installed it with pip initially. I'll recheck for stale files and reopen the issue for numba if a thorough cleanup shouldn't help.

**Comment by ml31415** [comment]
For the record, there was an old .egg-info folder lingering around in the dist-packages folder, which had survived a previous `pip uninstall` for some reasons, which had caused the problem.
