### ISSUE TITLE
Fail to compile with llvm 3.7.0

### ISSUE THREAD

**Issue by guotsuan** [numba/llvmlite#105]
llvmlite fail to compile with llvm 3.7.0

================================================================
targets.cpp:7:43: fatal error: llvm/Target/TargetLibraryInfo.h: No such file or directory
compilation terminated.
Makefile.linux:17: recipe for target 'libllvmlite.so' failed
make: *** [libllvmlite.so] Error 1
Traceback (most recent call last):
  File "ffi/build.py", line 114, in <module>
    main()
  File "ffi/build.py", line 104, in main
    main_posix('linux', '.so')
  File "ffi/build.py", line 96, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
error: command '/usr/bin/python' failed with exit status 1

**Comment by pitrou** [comment]
Well, yes, current LLVM is compatible with LLVM 3.6. We may switch to LLVM 3.7 in the future, but we don't support several versions at once, since the APIs break at each release.
See http://llvmlite.pydata.org/en/latest/install/index.html

**Comment by skycaptain** [comment]
As of 0.9 llvmlite supports llvm-3.7. But I'm still getting this error on Ubuntu Trusty with all llvm-packages installed and LLVM_CONFIG set.
